@url= http://localhost:5000

### all projects
GET {{ url }}/projects
Content-Type: application/json

### create
POST {{url}}/projects
Content-Type: application/json

{
    "name": "Note",
    "image": "note.png",
    "secondImage": "note2.png",
    "description": "Backend Project",
    "tools": "HTML, SCSS, JavaScript, NodeJS, MongoDB",
    "link": "https://note-app-rust.vercel.app",
    "github": "https://github.com/elis-11/note-app"
}

### update
PATCH {{url}}/projects/62d52c99c392c39fcb537e0a
content-type: application/json

{
    "name": "New Tralala",
    "image": "cloud.png",
    "secondImage": "cloud2.png",
    "description": "Tralala",
    "tools": "cloud.png",
    "link": "cloud.png",
    "github": "cloud.png"
}

### delete
DELETE {{url}}/projects/62d52e9fc392c39fcb537e2a

### single project
GET {{ url }}/projects/62d4749a42ebdbfb58561489
Content-Type: application/json
