@url = http://localhost:5000

### all users
GET {{ url }}/users

### delete user
DELETE {{url}}/users/62cc72d15781638449d5e65e
Content-Type: application/json

### create user / signup
POST {{url}}/users
Content-Type: application/json

{
    "name": "Leonid",
    "email": "leonid@gmail.com",
    "password": "leonid"
}

### login user
POST {{url}}/users/login
Content-Type: application/json

{
    "email": "leonid@gmail.com",
    "password": "leonid"
}

### logout user
GET {{url}}/users/logout

### update user
PATCH {{url}}/users/62cc2b03a7ec45fc179ed1e5
Content-Type: application/json

{
    "name": "Jannat",
    "email": "jannat@gmail.com",
    "password": "jannat"
}

### single user
GET {{ url }}/users/me
Content-Type: application/json
