@url = http://localhost:5000

### all users
GET {{ url }}/users
Content-Type: application/json

### delete user
DELETE {{url}}/users/62cb0550f054199ee3719ae5
Content-Type: application/json

### create user / signup
POST {{url}}/users
Content-Type: application/json

{
    "name": "Emili",
    "email": "emili@gmail.com",
    "password": "emili"
}

### login user
POST {{url}}/users/login
Content-Type: application/json

{
    "email": "malf@gmail.com",
    "password": "ralf"
}

### single user
GET {{ url }}/users/me
Content-Type: application/json

### logout user
GET {{url}}/users/logout

### update user
PATCH {{url}}/users/62cc2b03a7ec45fc179ed1e5
Content-Type: application/json

{
    "name": "Jannat",
    "email": "jannat@gmail.com",
    "password": "jannat"
}
