@url = http://localhost:5000

### all users
GET {{ url }}/users

### delete user
DELETE {{url}}/users/62fc8e2b09f5b4232df80c6e

### create user / signup
POST {{url}}/users
Content-Type: application/json

{
    "name": "Ralf",
    "email": "ralf@gmail.com",
    "password": "ralf"
}

### login user
POST {{url}}/users/login
Content-Type: application/json

{
    "email": "leonid@gmail.com",
    "password": "leonid"
}

### logout user
GET {{url}}/users/logout

### update user
PATCH {{url}}/users/62cc2b03a7ec45fc179ed1e5
Content-Type: application/json

{
    "name": "Jannat",
    "email": "jannat@gmail.com",
    "password": "jannat"
}

### me user
GET {{ url }}/users/currentuser
Content-Type: application/json

### single user
GET {{ url }}/users/62bf30e8fd8e8b928ec2b5b1
